name: Bore Proxies 20
on: 
  workflow_dispatch:

jobs:
  spawn-proxy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    
    steps:
      - name: Install Gost & Bore
        run: |
          # Ставим Gost
          wget https://github.com/ginuerzh/gost/releases/download/v2.11.5/gost-linux-amd64-2.11.5.gz
          gunzip gost-linux-amd64-2.11.5.gz
          chmod +x gost-linux-amd64-2.11.5
          sudo mv gost-linux-amd64-2.11.5 /usr/local/bin/gost
          
          # Ставим Bore
          wget https://github.com/ekzhang/bore/releases/download/v0.5.0/bore-v0.5.0-x86_64-unknown-linux-musl.tar.gz
          tar -xf bore-v0.5.0-x86_64-unknown-linux-musl.tar.gz
          chmod +x bore
          sudo mv bore /usr/local/bin/bore

      - name: Start Proxy and Keep Alive
        run: |
          # 1. Запускаем прокси на 8080
          gost -L :8080 > /dev/null 2>&1 &
          
          # 2. Запускаем туннель bore
          bore local 8080 --to bore.pub > bore.log 2>&1 &
          
          # 3. Ждем 5 секунд, чтобы туннель подцепился
          sleep 5
          
          # 4. Вытаскиваем адрес из логов
          ADDRESS=$(grep -oE "bore.pub:[0-9]+" bore.log | head -n 1)
          
          echo "****************************************"
          echo "ТВОЙ ПРОКСИ НОМЕР ${{ matrix.id }}:"
          echo "АДРЕС: $ADDRESS"
          echo "****************************************"
          
          # 5. ДЕРЖИМ МАШИНУ ВКЛЮЧЕННОЙ 1 ЧАС
          sleep 3600
